### ISSUE TITLE
reset view setting and reload

### ISSUE THREAD

**Issue by newshades** [sherrmann/Spoolman-NG#389]
[8d6725cc_spoolman_ng_2026-08-12T13-00-45.054Z.log](https://github.com/user-attachments/files/30982123/8d6725cc_spoolman_ng_2026-08-12T13-00-45.054Z.log)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Spoolman Host (please complete the following information):**
 - Installation type: [Docker or Standalone] Home assistant  Installation method
Home Assistant OS
Core
2026.8.1
Supervisor
2026.07.5
Operating System
18.2
Frontend
20260729.6
 - Installed version: [e.g. 0.17.0, can be found at the bottom of your spoolman website if you don't know]
 - OS and Distro: [e.g. Ubuntu, Raspbian]
 - Database type: [SQLite, PostgreSQL, etc]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, iOS, Android, ...]
 - Browser [e.g. Chrome, Firefox, Safari, ...]

**Additional context**
this seems to be happening when i add polymaker ABS. I have to uninstall SM and reinstall to get SM up and running. I have given you my logs and screenshots. 
<img width="1266" height="414" alt="Image" src="https://github.com/user-attachments/assets/7ebd181a-de8e-4c59-a6d5-1dd86b1fe34b" />

**Comment by 7R0J4Ner** [comment]
Same problem here.

<img width="3432" height="825" alt="Image" src="https://github.com/user-attachments/assets/f1f58828-ee57-4993-9445-b51bd9c24644" />

The [Edge build](https://github.com/sherrmann/Spoolman-NG/pkgs/container/spoolman-ng/1114135240?tag=edge) works for me on latest Firefox

**Comment by raf802** [comment]
Edge build worked for me for about a day. It worked yesterday after upgrading from :latest. Now I am experiencing the same issue on the Edge build. This is with both Firefox and MS Edge.

**Comment by newshades** [comment]
So my database is working just fine, I found out that sometimes i can do Spoolman:8000/create or vendor to get the page working for a few minutes.  But My full work around right now is to use the app called SpoolSync https://play.google.com/store/apps/details?id=tech.quiix.spoolsync&hl=en_US  and I get full access to database to edit everything. And i can now read/write rfid tags.

**Comment by sherrmann** [comment]
**v2026.8.0 is out and contains the fix for this.**

The crash was fixed on 8 Aug, but it sat unreleased — the newest release until now was
v2026.7.14 from 20 July, so `:latest`, the HA add-on and Moonraker installs never got it.
Sorry for the delay.

@raf802 @newshades — could you update and let me know if it's resolved? If it isn't, please
post the browser console stack trace (which page it names), and do one hard-reload with the
cache disabled first to rule out a stale cached bundle.

We also found a separate bug while investigating: any non-UI client (Moonraker, OctoPrint,
HA, third-party apps) could write an invalid weight that made the spool list fail server-side.
That fix is in #391 and will follow in a patch release.

**Comment by newshades** [comment]
So I stopped service then refreshed screen then updated and it looks to be working now.  If you need any help beta testing let me know.

**Comment by sherrmann** [comment]
**v2026.8.1 is out**, and it carries the follow-up fix I promised above.

Recap of what was wrong and what shipped where:

- The white screen itself (`TypeError: e.toFixed is not a function`) was fixed in **v2026.8.0** — a long float value being turned into a string and corrupting weight totals (#377 / #383). @newshades confirmed that resolved it.
- The related server-side hole — any non-UI client (Moonraker, OctoPrint, Home Assistant, third-party apps) could write a non-finite weight that made the spool list fail — was fixed in #391. That landed after the 2026.8.0 tag, which is why it needed this release. It also repairs rows already poisoned by such a write, so an instance that hit this recovers on upgrade without manual database surgery.

Closing this. @raf802 — if you still see it after updating to 2026.8.1 and doing one hard reload with the cache disabled, please reopen with the browser console stack trace and the page it names; a stale cached bundle looks exactly like the original bug.

Thanks both for the reports and for testing — the SpoolSync workaround in particular was useful signal that the data was fine and the failure was purely in rendering.
